apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "uchiwa.fullname" . }}
  labels:
    app: {{ template "uchiwa.name" . }}
    chart: {{ template "uchiwa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
  config.json : |-
{{- if .Values.config }}
{{ .Values.config | indent 6 }}
{{- else }}
    {
      "sensu": [

      ],
      "uchiwa": {
        "host": "0.0.0.0",
        "port": 3000,
        "refresh": 10,
        "loglevel": "info"
      }
    }
{{- end }}
