apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uchiwa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "uchiwa.name" . }}
    helm.sh/chart: {{ include "uchiwa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "uchiwa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:        
        app.kubernetes.io/name: {{ include "uchiwa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.podAnnotations }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 20
            timeoutSeconds: 10
            httpGet:
              path: /health/uchiwa
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 20
            timeoutSeconds: 10
            httpGet:
              path: /health/uchiwa
              port: http
          volumeMounts:
            - mountPath: /config/
              name: uchiwa-config        
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ template "uchiwa.fullname" . }}
          name: uchiwa-config    
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
